In [1]:
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("D:/CSV FILES/Iris.csv")

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
data.shape

(150, 6)

In [7]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# Train_Test_Split

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x = data.drop(columns = ['Species'])
y = data['Species']

In [10]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.25)

In [11]:
x_train.shape

(112, 5)

In [12]:
x_test.shape

(38, 5)

In [13]:
y_train.shape

(112,)

In [14]:
y_test.shape

(38,)

# LOGISTIC REGRESSION

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred = model.predict(x_train)

In [17]:
from sklearn.metrics import confusion_matrix,classification_report

In [18]:
cm = confusion_matrix(y_train, y_pred)
print ("Confusion Matrix : ", cm)

Confusion Matrix :  [[34  0  0]
 [ 5 33  0]
 [ 0  1 39]]


In [19]:
clf=(classification_report(y_train, y_pred))
print ("Classification report:", clf)

Classification report:                  precision    recall  f1-score   support

    Iris-setosa       0.87      1.00      0.93        34
Iris-versicolor       0.97      0.87      0.92        38
 Iris-virginica       1.00      0.97      0.99        40

       accuracy                           0.95       112
      macro avg       0.95      0.95      0.95       112
   weighted avg       0.95      0.95      0.95       112



In [20]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_train, y_pred)*100)

Accuracy :  94.64285714285714


# SUPPORT VECTOR CLASSIFIER

In [21]:
from sklearn.svm import SVC
svc= SVC()
svc.fit(x_train, y_train)

SVC()

In [22]:
y_pred = svc.predict(x_test)

In [23]:
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix :", cm)

Confusion Matrix : [[16  0  0]
 [ 0 11  1]
 [ 0  0 10]]


In [24]:
clf=(classification_report(y_test, y_pred))
print ("Classification report:", clf)

Classification report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        38
      macro avg       0.97      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



In [25]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred)*100)

Accuracy :  97.36842105263158


## K-NEAREST NEIGHBORS CLASSIFIER

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
y_pred=knn.predict(x_test)

In [28]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy_Score:", accuracy*100)

clf=classification_report(y_test,y_pred)
print("Classification_Report:\n",clf)

Accuracy_Score: 97.36842105263158
Classification_Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        38
      macro avg       0.97      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38

